### ISSUE TITLE
Malicious code and some little problems

### ISSUE THREAD

**Issue by CubicPill** [BorisChenCZY/Auto-judge-for-Sakai#1]
Hi Boris,
In your code for executing the compiled .class file, I found this:
```
test = os.system('java {} < ./{} >tmp.result'.format(class_name, single_test_file))
```
It doesn't seem to have a mechanism to prevent the (potential) malicious code from executing. And the output of ```stdout``` and ```stderr``` does not seems to be handled separately. So real result and logs may be mixed together.
Also, in the code for compiling the .java files:
```
os.system('javac ./{}.java'.format(class_name))
```
Seems compile errors will not be reported to ```error.md``` correctly.

**Comment by ZhenyuC-Dev** [comment]
Yeah, that's a problem. But so far I've not found a proper solution to this. Sorry about that.

If you do have some idea about how to solve this, please do let me know.

**Comment by lightsing** [comment]
1. First you need to drop the testing program's privilege. (example. sudo -u nobody -g nobody <exec>)
2. Then, using cgroups limit the potential harmful operation. For example, writing a huge file to exhaust disk space.
3. To avoid other potential problems, you'd better put them in a sandbox, container, virtual machine or any other thing to isolate it from the test machine.

Using docker can meet these requirements if you are not familiar with cgroups.
https://docs.docker.com/engine/admin/resource_constraints/

**Comment by ZhenyuC-Dev** [comment]
I've found out the solution and the code will be updated recently.

**Comment by ZhenyuC-Dev** [comment]
Uploaded.
